### ISSUE TITLE
[BUG] DELTA PRO Backup Reserve On/Off Switch is allways ON

### ISSUE THREAD

**Issue by NameIstSchonVergeben** [tolwi/hassio-ecoflow-cloud#180]
DELTA PRO Backup Reserve On/Off Switch is allways ON in HA, but OFF in the EcoFlow App.
If I change the Switch from ON to OFF in HA - after 4 Sec. the Switch change to ON by itself.

![snip-backuppower-on-off](https://github.com/tolwi/hassio-ecoflow-cloud/assets/153944468/63c869ac-99d3-4309-98c3-fd9de95cd440)

If I change the Switch in the App, it have no reaction in HA - If I switch in HA it have no reaction in the App - something must be wrong.

The backup setting value slider works and syncs immediately with the app.

**Comment by NameIstSchonVergeben** [comment]
... more Informations about:
how I find out, the Switch "Backup Reserve On/Off" disabled the Function, when I move only the Switch in the OFF Position.

Moving the switch has no effect, if the backup function is already deactivated in the app.
Even if the switch reactivates itself after the 4 seconds, it has no effect.

The Value of the Backup Reserve change AND activate itself only when I use the slider. So I can deaktivate the Function over the Switch.

When the DeltaPro wake up in the Morning (Status: assume_online), the Value of den Backup Reserve goes to 53 - when I change the Value back to 30 it aktivate the Funktion Backup Reserve. Over the Switch I disable it again.

Anyway - thanks a lot to all Dev's for this helpfull Repository.

**Comment by knyghtryda** [comment]
@NameIstSchonVergeben I have a fix for this, but forgot about it after implementing it locally.  This is a reminder to myself to get this (and some other Delta Pro fixes) into a PR.

**Comment by NameIstSchonVergeben** [comment]
@knyghtryda Thank you very much for taking on the problem

**Comment by rtorchia** [comment]
Just wanted to mention that this also is occurring with my Delta 2

**Comment by NameIstSchonVergeben** [comment]
@knyghtryda Hello, do you know when there will be an update that fixes this problem? Thanks!

**Comment by knyghtryda** [comment]
> @knyghtryda Hello, do you know when there will be an update that fixes this problem? Thanks!
> 
> 

I have updated the code and it's currently on the main branch. Just gotta have @tolwi make a release. Also, try reloading the integration and getting some log info. I am not actually seeing what would be causing your specific issue.

**Comment by NameIstSchonVergeben** [comment]
@knyghtryda Thanks for the quick reply. I re-downloaded the integration and the issue still exists... Hence the question.

**Comment by NameIstSchonVergeben** [comment]
@knyghtryda Sorry - but I made Yesterday the Update to v0.13.2 and the Issue with the switch always exist. After ~5 Sec. he move back in the ON Position. HA ist up to date.

**Comment by SergiyUKR** [comment]
I was also annoyed by this bug and decided to fix it.
It turns out that the problem is here (in my case it's for Delta 2):
https://github.com/tolwi/hassio-ecoflow-cloud/blob/f41560a471af88bf702dc4226ffac3c069f1b9f2/custom_components/ecoflow_cloud/devices/delta2.py#L162
Instead of `pd.bpPowerSoc` you need to use `pd.watchIsConfig`. 


Also you can change the value of `bpPowerSoc` in params to 50.
https://github.com/tolwi/hassio-ecoflow-cloud/blob/f41560a471af88bf702dc4226ffac3c069f1b9f2/custom_components/ecoflow_cloud/devices/delta2.py#L165
 As it is now if you enable backup from HA it sends the value as 1% and it's not valid (should be min 5%), but ecoflow changes it to 5%
 
 Hope, it will help

**Comment by NameIstSchonVergeben** [comment]
@SergiyUKR 
Thank you very much for taking the time to tell me this.

The problem is still there even after 2 updates, I don't know why the developers don't want to fix it.

Your Solution - It's a bit too complicated for me personally - I don't want to mess anything up.

I've currently solved the problem with the backup power function with a switchable socket that lets me charge the DeltaPro with power in case of needing a load and the battery level controls the switching. It works and that's the main thing.

Thanks anyway - ..

**Comment by SergiyUKR** [comment]
@NameIstSchonVergeben 
I've created a fork of integration here
https://github.com/SergiyUKR/hassio-ecoflow-cloud/
Could you test it on your Delta Pro?
If it works, I'll create a pull request to the main repository

**Comment by NameIstSchonVergeben** [comment]
@SergiyUKR 
Please excuse the late reply - I missed your post.

I tested it and it works fantastically.

If I change the backup switch in the app, HA displays the status.

In HA the switch is and remains off.

No matter where you change it, it synchronizes within 1-3 seconds

Thank you for your solution.

**Comment by SergiyUKR** [comment]
I'm glad that I could help!

I've created a pull request to main repository, so, hopefully, it will be available soon for everybody

**Comment by NameIstSchonVergeben** [comment]
@SergiyUKR 
well, I see, tolwi merged the Solution. So I close the Issue now.
Anyway - thanks a lot for your pretty help - have a great time
