### ISSUE TITLE
I'm not getting readings from many of the sensors

### ISSUE THREAD

**Issue by philmulley** [tolwi/hassio-ecoflow-cloud#231]
I've just installed the integration (on a Delta2) and I'm missing readings from a lot of the sensors.

![sensors](https://github.com/tolwi/hassio-ecoflow-cloud/assets/24371633/33db226a-4075-498b-bea2-c4e7774b0816)

Firmware V1.0.1.123 & V1.0.6.28 (WiFi).

Home Assistant Core 2024.4.3

Some things are working: like turning on and off the USB power outputs, for example. Nothing about the battery though.

What information would be helpful to yourself in diagnosis?

**Comment by Nid01** [comment]
You can activate debugging in the integration for a short period of time and in the file you get after stopping the debugging there is JSON data.
This JSON data needs to be analyzed, how it differs from the DELTA 2 definition of the integration, so it would help to get a look into the JSON data.

**Comment by maddinhome** [comment]
I also have the same problem.

Core 2024.5.0b0
Supervisor 2024.04.3
Operating System 12.2
Frontend 20240424.1 

Logger: custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt
Quelle: custom_components/ecoflow_cloud/mqtt/ecoflow_mqtt.py:309
Integration: EcoFlow-Cloud ([Dokumentation](https://github.com/tolwi/hassio-ecoflow-cloud), [Probleme](https://github.com/tolwi/hassio-ecoflow-cloud/issues))
Erstmals aufgetreten: 13:15:48 (918 Vorkommnisse)
Zuletzt protokolliert: 14:48:30
Detected that custom integration 'ecoflow_cloud' calls async_write_ha_state from a thread at custom_components/ecoflow_cloud/entities/__init__.py, line 85: self.async_write_ha_state(). Please report it to the author of the 'ecoflow_cloud' custom integration.

**Comment by maddinhome** [comment]
look here:  https://github.com/tolwi/hassio-ecoflow-cloud/issues/232

maybe the solution.....

**Comment by KarinBerg** [comment]
This issue will be fix with this pull request https://github.com/tolwi/hassio-ecoflow-cloud/pull/234 once it is merge and released by the repository owner @tolwi 

In the meantime, you can modify the files from the pull request locally on your Home Assistant installation.

**Comment by Nid01** [comment]
@pauldcomanici
For DELTA2's battery level the integration is looking for `bms_emsStatus.lcdShowSoc` values.
I do not own a DELTA2 so I don't know if the integration is looking for the wrong key.
Since the debug logging of the integration didn't log the received packages as I previously thought, you should have the option `download diagnostics`.
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/30300755/3e6e34cf-b9b8-45a8-aba5-68888b24202e)

There you should be able to find `data` which contains the received messages from your DELTA2.
When you don't find that you might need to add the DELTA2 as `diagnostic` so the raw messages get stored.
From that we could find out, what might be off in your situation.

**Comment by pauldcomanici** [comment]
I did the "download diagnostics" and I couldn't find battery data. See bellow the content:
```
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.5.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Europe/Bucharest",
    "os_name": "Linux",
    "os_version": "6.6.28-haos-raspi",
    "supervisor": "2024.05.1",
    "host_os": "Home Assistant OS 12.3",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "ecoflow_cloud": {
      "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
      "version": "0.13.2",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "landroid_cloud": {
      "documentation": "https://github.com/MTrab/landroid_cloud/blob/master/README.md",
      "version": "5.0.4",
      "requirements": [
        "pyworxcloud==4.1.13"
      ]
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    },
    "shelly": {
      "documentation": "https://github.com/StyraHem/ShellyForHASS/blob/master/README.md",
      "version": "1.0.5",
      "requirements": [
        "pyShelly==1.0.3",
        "paho-mqtt==1.6.1",
        "websocket-client"
      ]
    }
  },
  "integration_manifest": {
    "domain": "ecoflow_cloud",
    "name": "Ecoflow-Cloud",
    "codeowners": [
      "@tolwi"
    ],
    "config_flow": true,
    "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/tolwi/hassio-ecoflow-cloud/issues",
    "requirements": [
      "paho-mqtt==1.6.1",
      "reactivex==4.0.4",
      "protobuf>=4.23.0"
    ],
    "version": "0.13.2",
    "is_built_in": false
  },
  "data": {
    "device": "DELTA_2",
    "params": {
      "mppt.beepState": 0,
      "mppt.cfgAcEnabled": 1,
      "mppt.cfgAcXboost": 0,
      "pd.acAutoOutConfig": 1,
      "pd.bpPowerSoc": 0,
      "pd.carState": 0,
      "pd.dcOutState": 1,
      "pd.pvChgPrioSet": 0
    },
    "set": [
      {
        "from": "HomeAssistant",
        "id": "999918844",
        "moduleType": 5,
        "operateType": "quietMode",
        "params": {
          "enabled": 0
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918842",
        "moduleType": 1,
        "operateType": "watthConfig",
        "params": {
          "bpPowerSoc": 0,
          "minChgSoc": 0,
          "isConfig": 0,
          "minDsgSoc": 0
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918840",
        "moduleType": 5,
        "operateType": "mpptCar",
        "params": {
          "enabled": 0
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918838",
        "moduleType": 1,
        "operateType": "pvChangePrio",
        "params": {
          "pvChangeSet": 0
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918836",
        "moduleType": 5,
        "operateType": "acOutCfg",
        "params": {
          "enabled": 255,
          "out_voltage": -1,
          "out_freq": 255,
          "xboost": 0
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918834",
        "moduleType": 1,
        "operateType": "dcOutCfg",
        "params": {
          "enabled": 1
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918832",
        "moduleType": 5,
        "operateType": "acOutCfg",
        "params": {
          "enabled": 1,
          "out_voltage": -1,
          "out_freq": 255,
          "xboost": 255
        },
        "version": "1.0"
      },
      {
        "from": "HomeAssistant",
        "id": "999918830",
        "moduleType": 1,
        "operateType": "acAutoOutConfig",
        "params": {
          "acAutoOutConfig": 1,
          "minAcOutSoc": 5
        },
        "version": "1.0"
      }
    ],
    "set_reply": [],
    "get": [
      {
        "from": "HomeAssistant",
        "id": "999918843",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918841",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918839",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918837",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918835",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918833",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918831",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918829",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      },
      {
        "from": "HomeAssistant",
        "id": "999918828",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      }
    ],
    "get_reply": [],
    "raw_data": []
  }
}
```
Am I missing something?

**Comment by philmulley** [comment]
Following on from Nid01's comment I've also downloaded the json file to see if this contains anything of use to you

`{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2024.5.3",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/London",
    "os_name": "Linux",
    "os_version": "4.19.0-26-amd64",
    "run_as_root": true
  },
  "custom_components": {
    "omnik_inverter": {
      "documentation": "https://github.com/robbinjanssen/home-assistant-omnik-inverter",
      "version": "2.6.4",
      "requirements": [
        "omnikinverter==1.0.0"
      ]
    },
    "octopus_energy": {
      "documentation": "https://bottlecapdave.github.io/HomeAssistant-OctopusEnergy",
      "version": "11.0.0",
      "requirements": []
    },
    "octopusagile": {
      "documentation": "https://github.com/markgdev/home-assistant_OctopusAgile",
      "version": "2021.3.0b0",
      "requirements": []
    },
    "braviatv_psk": {
      "documentation": "https://github.com/custom-components/media_player.braviatv_psk",
      "version": "0.4.2",
      "requirements": [
        "pySonyBraviaPSK==0.2.4"
      ]
    },
    "monitor_docker": {
      "documentation": "https://github.com/ualex73/monitor_docker",
      "version": "1.10",
      "requirements": [
        "aiodocker==0.21.0",
        "python-dateutil==2.8.2"
      ]
    },
    "uptime_kuma": {
      "documentation": "https://github.com/meichthys/uptime_kuma/blob/main/README.md",
      "version": "2.1.0",
      "requirements": [
        "pyuptimekuma-hass"
      ]
    },
    "auto_backup": {
      "documentation": "https://github.com/jcwillox/hass-auto-backup",
      "version": "1.4.1",
      "requirements": []
    },
    "navien_water_heater": {
      "documentation": "https://www.github.com/nikshriv/hass_navien_water_heater",
      "version": "1.0.1",
      "requirements": [
        "AWSIoTPythonSDK"
      ]
    },
    "alarmo": {
      "documentation": "https://github.com/nielsfaber/alarmo",
      "version": "v1.10.1",
      "requirements": []
    },
    "tapo": {
      "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100",
      "version": "3.1.2",
      "requirements": [
        "plugp100==5.1.3"
      ]
    },
    "trakt": {
      "documentation": "https://github.com/custom-components/sensor.trakt/blob/master/README.md",
      "version": "2.0.3",
      "requirements": [
        "trakt==2.14.0"
      ]
    },
    "ecoflow_cloud": {
      "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
      "version": "0.13.2",
      "requirements": [
        "paho-mqtt==1.6.1",
        "reactivex==4.0.4",
        "protobuf>=4.23.0"
      ]
    },
    "tplink_router": {
      "documentation": "",
      "version": "1.0.0",
      "requirements": []
    },
    "presence_simulation": {
      "documentation": "https://github.com/slashback100/presence_simulation",
      "version": "4.8",
      "requirements": []
    },
    "ble_monitor": {
      "documentation": "https://github.com/custom-components/ble_monitor",
      "version": "12.11.1",
      "requirements": [
        "pycryptodomex>=3.18.0",
        "janus>=1.0.0",
        "aioblescan>=0.2.14",
        "btsocket>=0.2.0",
        "pyric>=0.1.6.3"
      ]
    },
    "powercalc": {
      "documentation": "https://github.com/bramstroker/homeassistant-powercalc",
      "version": "v1.12.2",
      "requirements": [
        "numpy>=1.21.1"
      ]
    },
    "hacs": {
      "documentation": "https://hacs.xyz/docs/configuration/start",
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "watchman": {
      "documentation": "https://github.com/dummylabs/thewatchman",
      "version": "0.5.1",
      "requirements": [
        "prettytable==3.0.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "ecoflow_cloud",
    "name": "Ecoflow-Cloud",
    "codeowners": [
      "@tolwi"
    ],
    "config_flow": true,
    "documentation": "https://github.com/tolwi/hassio-ecoflow-cloud",
    "iot_class": "cloud_push",
    "issue_tracker": "https://github.com/tolwi/hassio-ecoflow-cloud/issues",
    "requirements": [
      "paho-mqtt==1.6.1",
      "reactivex==4.0.4",
      "protobuf>=4.23.0"
    ],
    "version": "0.13.2",
    "is_built_in": false
  },
  "data": {
    "device": "DELTA_2",
    "params": {},
    "set": [],
    "set_reply": [],
    "get": [
      {
        "from": "HomeAssistant",
        "id": "999956240",
        "moduleType": 0,
        "operateType": "latestQuotas",
        "params": {},
        "version": "1.1"
      }
    ],
    "get_reply": [],
    "raw_data": []
  }
}`

**Comment by Nid01** [comment]
@pauldcomanici @philmulley
I'm surprised that `params` is containing no data. That's what we are missing.
I think you might have the same issue as https://github.com/tolwi/hassio-ecoflow-cloud/issues/237#issue-2293764186.

**Comment by pauldcomanici** [comment]
I look over #237, and the port is not a problem for me. I enabled debug logging and this is what I get:
```
2024-05-15 08:05:11.488 WARNING (SyncWorker_6) [homeassistant.loader] We found a custom integration ecoflow_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-15 08:05:21.557 INFO (SyncWorker_1) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Login to EcoFlow API https://api.ecoflow.com/auth/login
2024-05-15 08:05:21.891 INFO (SyncWorker_1) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Successfully logged in:
2024-05-15 08:05:21.891 INFO (SyncWorker_1) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Requesting IoT MQTT credentials https://api.ecoflow.com/iot-auth/app/certification
2024-05-15 08:05:22.104 INFO (SyncWorker_1) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Successfully extracted account: app-ID_EDITED
2024-05-15 08:05:22.181 INFO (MainThread) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Connecting to MQTT Broker mqtt-e.ecoflow.com:8883
2024-05-15 08:05:22.426 INFO (Thread-5 (_thread_main)) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Subscribed to MQTT topic /app/device/property/SN_EDITED
2024-05-15 08:05:27.910 DEBUG (MainThread) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Sending {"from": "HomeAssistant", "id": "999958113", "version": "1.1", "moduleType": 0, "operateType": "latestQuotas", "params": {}} :(0, 2)(False)
2024-05-15 08:21:47.736 DEBUG (SyncWorker_6) [custom_components.ecoflow_cloud.switch] Updating switch ecoflow-SN_EDITED-pd-dcOutState to 1
2024-05-15 08:21:47.741 DEBUG (SyncWorker_6) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Sending {"from": "HomeAssistant", "id": "999958114", "version": "1.1", "moduleType": 0, "operateType": "latestQuotas", "params": {}} :(0, 3)(False)
2024-05-15 08:21:47.743 DEBUG (SyncWorker_6) [custom_components.ecoflow_cloud.mqtt.ecoflow_mqtt] Sending {"from": "HomeAssistant", "id": "999958115", "version": "1.0", "moduleType": 1, "operateType": "dcOutCfg", "params": {"enabled": 1}} :(0, 4)(False)
```
looks pretty similar to @philmulley

**Comment by nils-82** [comment]
Hello,
I have updated to the latest version and that doesn't seem to work anymore. See screenshots attached . Was working fine before the update. Hope this can be fix. Regards 
![Screenshot_20240515_122335_Home Assistant](https://github.com/tolwi/hassio-ecoflow-cloud/assets/96875874/678f01a7-939e-4ec3-9ee8-e3aae92f0ada)

**Comment by Nid01** [comment]
@pauldcomanici
Where did you ask for developer account?
When asked at https://developer-eu.ecoflow.com/us/ then you should know, that this is another newer API and not the one this integration is using.

**Comment by Nid01** [comment]
@nils-82
Please provide exact version numbers as "latest version" can easily be mistaken.

**Comment by nils-82** [comment]
> @nils-82 Please provide exact version numbers as "latest version" can easily be mistaken.

I'm using version 0.13.3

**Comment by philmulley** [comment]
I've made the changes to the 2 files as suggested in #247 but I'm still not getting any readings.

**Comment by philmulley** [comment]
> @pauldcomanici @philmulley I'm surprised that `params` is containing no data. That's what we are missing. I think you might have the same issue as [#237 (comment)](https://github.com/tolwi/hassio-ecoflow-cloud/issues/237#issue-2293764186).

I've made the changes to the 2 files as suggested in #247 but I'm still not getting any readings.

**Comment by Nid01** [comment]
@philmulley
Is your issue solved with the newest version https://github.com/tolwi/hassio-ecoflow-cloud/releases/tag/v0.13.3 of the integration?

**Comment by philmulley** [comment]
No, sadly I'm still not getting any readings.  Is there anything else I can
supply or test to help with fault finding?

Thanks so much for all your efforts.

Phil

**Comment by pauldcomanici** [comment]
wow, this is crazy, you are right. I removed the integration then added it again and now it works.

**Comment by philmulley** [comment]
I'm thinking that perhaps HA cached things,  I did make the adjustments to
the files as suggested my some on this thread: but perhaps HA was not
reading the newer version of the files until I re installed.

Just a thought.

Phil
